In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/online_retail/clean_retail.csv",
    low_memory=False
)

df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"]
)

print(df.shape)

(1041670, 9)

In [2]:
monthly = (
    df.groupby(
        pd.Grouper(
            key="InvoiceDate",
            freq="ME"
        )
    )
    .agg({
        "Revenue":"sum",
        "Customer ID":"nunique",
        "Invoice":"nunique",
        "Quantity":"sum"
    })
)

monthly.columns = [
    "Revenue",
    "Customers",
    "Orders",
    "Quantity"
]

monthly = monthly.reset_index()

monthly.head()

  InvoiceDate     Revenue  Customers  Orders  Quantity
0  2009-12-31  825685.760        955    1682    426981
1  2010-01-31  652708.502        720    1105    391525
2  2010-02-28  553339.736        772    1201    382781
3  2010-03-31  833570.131       1057    1681    527401
4  2010-04-30  681528.992        942    1462    368198

In [3]:
monthly["Revenue_Change"] = (
    monthly["Revenue"]
    .pct_change()
)

monthly["Customer_Change"] = (
    monthly["Customers"]
    .pct_change()
)

monthly["Order_Change"] = (
    monthly["Orders"]
    .pct_change()
)

monthly["Quantity_Change"] = (
    monthly["Quantity"]
    .pct_change()
)

monthly = monthly.dropna()

monthly.head()

,InvoiceDate,Revenue,Customers,Orders,Quantity,Revenue_Change,Customer_Change,Order_Change,Quantity_Change
1,2010-01-31,652708.502,720,1105,391525,-0.209495,-0.246073,-0.343044,-0.083039
2,2010-02-28,553339.736,772,1201,382781,-0.152241,0.072222,0.086878,-0.022333
3,2010-03-31,833570.131,1057,1681,527401,0.506435,0.369171,0.399667,0.377814
4,2010-04-30,681528.992,942,1462,368198,-0.182398,-0.108798,-0.130280,-0.301863
5,2010-05-31,659858.860,966,1500,397206,-0.031796,0.025478,0.025992,0.078784

In [5]:
import sys

print(sys.executable)

c:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe